robots:
  - proto: "Wolfgang"
    poses: "wolfgang_poses.yaml"
    height: 0.45
  - proto: "RobocupRobot"
    poses: ""
    height: 0.25
  - proto: "Prometheus"
    poses: ""
    height: 0.45
  - proto: "Bez"
    poses: ""
    height: 0.37
  - proto: "RoboCup_GankenKun"
    poses: ""
    height: 0.44
  - proto: "RFCRobot2016"
    poses: ""
    height: 0.44